project:
  type: book
  output-dir: docs
  preview: 
    browser: true
    port: 4200

book:
  cover-image: images/pedics-notes-cover.jpg
  favicon: images/pedics-notes-cover.jpg
  reader-mode: false
  page-navigation: true
  cover-image-alt: "Logo"
  title: "Pediatrics Notes"
  author: "Department of Child Health <br> SMS, KNUST <br> KATH"
  date: today
  sidebar: 
    title: Contents
    search: true
    style: docked
  page-footer:
    background: light
    center: "Compiled by: Dr Samuel Blay Nguah"
    left: KNUST
    right: KATH
  chapters:
    - index.qmd
    - contributors.qmd
    - gen-child-hx-exam.qmd
    - gen-growh-development.qmd
    - gen-anthropometry.qmd
    - gen-acid-base.qmd
    - part: "<span style='font-weight:bold; color: black;'>Basic Critical Care</span>"
      chapters: 
        - cc-critical-care.qmd
        - cc-cardiovascular-dysfunction.qmd
    - part: "<span style='font-weight:bold; color: black;'>Neonatology</span>"
      chapters: 
        - neo-neonate-hx-exam.qmd
        - neo-neonatal-delivery-pathologies.qmd
        - neo-neonatal-emergencies.qmd
        - neo-neonatal-jaundice.qmd
        - neo-newborn-delivery-resus.qmd
        - neo-preterm-low-birth-weight.qmd
        - neo-newborn-feeding.qmd
    - part: "<span style='font-weight:bold; color: black;'>Pulmonology</span>"
      chapters: 
        - resp-basics.qmd
        - resp_respiratory_failure.qmd
        - resp-asthma.qmd
        - resp-bronchiolitis.qmd
        - resp-croup.qmd
        - resp-pneumonia.qmd
        - resp-broncho-dysp.qmd
    - part: "<span style='font-weight:bold; color: black;'>Cardiology</span>"
      chapters: 
        - cvs-intro.qmd
        - cvs-evaluation.qmd
        - cvs-heart-failure.qmd
        - cvs-asd.qmd
        - cvs-vsd.qmd
        - cvs-pda.qmd
        - cvs-coa.qmd
        - cvs-tof.qmd
        - cvs-rhd.qmd
        - cvs-inf-endo.qmd
        - cvs-emf.qmd
        - cvs-miscellaneous.qmd
    - part: "<span style='font-weight:bold; color: black;'>Infectious Diseases</span>"
      chapters: 
        - id-enteric-fever.qmd
        - id-hiv.qmd
        - id-sepsis.qmd
        - id-tuberculosis.qmd
        - id-immunization.qmd
        - id-meningitis.qmd
        - id-osteomyelitis.qmd
    - part: "<span style='font-weight:bold; color: black;'>Oncology</span>"
      chapters: 
        - onco-principles.qmd
        - onco-oncological-emergencies.qmd
        - onco-leukemia.qmd
        - onco-lymphoma.qmd
        - onco-retinoblastoma.qmd
        - onco-wilms-tumor.qmd
        - onco-other-tumours.qmd
    - part: "<span style='font-weight:bold; color: black;'>Nephrology</span>"
      chapters: 
        - nep-renal-disorders.qmd
        - nep-hypertension.qmd
        - nep-uti.qmd
        - nep-hematuria.qmd
        - nep-nephrotic-syndrome.qmd
        - nep-nephritic-syndrome.qmd
        - nep-kidney-failure.qmd
        - neph-obstructive-uropathy.qmd
    - part: "<span style='font-weight:bold; color: black;'>Neurology</span>"
      chapters: 
        - neuro-spectrum.qmd
        - neuro-spectrum-2.qmd
        - neuro-cns-infections.qmd
        - neuro-cerebral-palsy.qmd
        - neuro-seizure-disorders.qmd
        - neuro-neuromuscular.qmd 
        - neuro-neurocutaneous-synd.qmd
        - neuro-stroke.qmd
    - part: "<span style='font-weight:bold; color: black;'>Endocrinology</span>"
      chapters: 
        - endo-spectrum.qmd
        - endo-dm.qmd
        - endo-thyroid.qmd
        - endo-adrenal.qmd
        - endo-pituitary.qmd
        - endo-calcium-bone.qmd
        - endo-reproductive.qmd
        - endo-growth.qmd
    - part: "<span style='font-weight:bold; color: black;'>Haematology</span>"
      chapters:
        - haem-basics.qmd
        - haem-sickle-cell.qmd
        - haem-hemoglobinopathies.qmd
        - haem-anemia.qmd
        - haem-bleeding-disorders.qmd
        - haem-transfusion.qmd
        - haem-bone-marrow-failure.qmd
    - part: "<span style='font-weight:bold; color: black;'>Gastroenterology</span>"
      chapters: 
        - gast-nutrition.qmd
        - gast-malnutrition.qmd
        - gast-liver-disorders.qmd
        - gast-prolonged-jaundice.qmd
        - gast-diarrhoea.qmd
        - gast-vitamins.qmd
    - part: "<span style='font-weight:bold; color: black;'>Dermatology</span>"
      chapters: 
        - derm-impetigo.qmd
        - derm-fungal.qmd
        - derm-alopecia.qmd
        - derm-eczema.qmd
        - derm-dermatitis.qmd
        - derm-scabies.qmd
    - part: "<span style='font-weight:bold; color: black;'>Home Accidents</span>"
      chapters: 
        - home-iron-poisoning.qmd
        - home-paracetamol.qmd
        - home-insecticides.qmd
        - home-caustic-soda.qmd
        - home-hydrocarbons.qmd
        - home-electrical.qmd
        - home-drowning.qmd
    - part: "<span style='font-weight:bold; color: black;'>Animal Bites</span>"
      chapters: 
        - bite-snake.qmd
        - bite-dog.qmd
        - bite-scorpion.qmd
    - part: "<span style='font-weight:bold; color: black;'>Common Syndrome</span>"
      chapters: 
        - synd-down.qmd
        - synd-edwards.qmd
        - synd-patau.qmd
        - synd-turners.qmd
        - synd-noonan.qmd
        - synd-digeorge.qmd
        - synd-williams.qmd
        - synd-fetal-alcohol.qmd
        - synd-fragilex.qmd
        - synd-prader-willi.qmd
    - part: "<span style='font-weight:bold; color: black;'>Parasitic Infections</span>"
      chapters: 
        - para-overview.qmd
        - para-malaria.qmd
    - part: "<span style='font-weight:bold; color: black;'>General Pediatrics</span>"
      chapters: 
        - gen-therapeutics.qmd
        - gen-congenital-malformations.qmd
        - gen-social-ethical-legal.qmd
        - gen-lab-investigations.qmd
        - gen-bedside-tests.qmd
        - gen-clinical-research.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    mainfont: Times New
    theme: 
        - cosmo
        - BookTheme.scss
  pdf:
    documentclass: scrreprt


